name: Publish package to npm

on:
  workflow_dispatch:          # manual trigger
  release:
    types: [published, released]        # fires on every release event

permissions:
  contents: read
  id-token: write             # required for --provenance

jobs:
  publish:
    # skip preâ€‘releases unless manually dispatched
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.release.prerelease == false }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # provenance links back to this commit

      - name: Setup Node.js (npm CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
#  Authentication Happen automatically with trusted publisher
      # - name: Authenticate to npm
        # run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.PUBLISH_TOKEN }}

      - name: Publish with provenance
        # env:
          # NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: npm publish --provenance --access public
